// Code generated by MockGen. DO NOT EDIT.
// Source: example/pkg/mysql.go
//
// Generated by this command:
//
//	mockgen -source=example/pkg/mysql.go -destination=example/mocks/mock_db_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDBFactory is a mock of DBFactory interface.
type MockDBFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDBFactoryMockRecorder
	isgomock struct{}
}

// MockDBFactoryMockRecorder is the mock recorder for MockDBFactory.
type MockDBFactoryMockRecorder struct {
	mock *MockDBFactory
}

// NewMockDBFactory creates a new mock instance.
func NewMockDBFactory(ctrl *gomock.Controller) *MockDBFactory {
	mock := &MockDBFactory{ctrl: ctrl}
	mock.recorder = &MockDBFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBFactory) EXPECT() *MockDBFactoryMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockDBFactory) Open(dsn string, opts ...gorm.Option) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	varargs := []any{dsn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Open", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockDBFactoryMockRecorder) Open(dsn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{dsn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDBFactory)(nil).Open), varargs...)
}
