// Code generated by MockGen. DO NOT EDIT.
// Source: example/dao/txrecord.go
//
// Generated by this command:
//
//	mockgen -source=example/dao/txrecord.go -destination=example/mocks/mock_tx_record_updater.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/hangtiancheng/yukino.go/apps/tcc_demo/example/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockTXRecordUpdater is a mock of TXRecordUpdater interface.
type MockTXRecordUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTXRecordUpdaterMockRecorder
	isgomock struct{}
}

// MockTXRecordUpdaterMockRecorder is the mock recorder for MockTXRecordUpdater.
type MockTXRecordUpdaterMockRecorder struct {
	mock *MockTXRecordUpdater
}

// NewMockTXRecordUpdater creates a new mock instance.
func NewMockTXRecordUpdater(ctrl *gomock.Controller) *MockTXRecordUpdater {
	mock := &MockTXRecordUpdater{ctrl: ctrl}
	mock.recorder = &MockTXRecordUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTXRecordUpdater) EXPECT() *MockTXRecordUpdaterMockRecorder {
	return m.recorder
}

// UpdateTXRecord mocks base method.
func (m *MockTXRecordUpdater) UpdateTXRecord(ctx context.Context, record *dao.TXRecordPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTXRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTXRecord indicates an expected call of UpdateTXRecord.
func (mr *MockTXRecordUpdaterMockRecorder) UpdateTXRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTXRecord", reflect.TypeOf((*MockTXRecordUpdater)(nil).UpdateTXRecord), ctx, record)
}
