// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pb/yukino.proto

package __

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YukinoCache_Get_FullMethodName    = "/pb.YukinoCache/Get"
	YukinoCache_Set_FullMethodName    = "/pb.YukinoCache/Set"
	YukinoCache_Delete_FullMethodName = "/pb.YukinoCache/Delete"
)

// YukinoCacheClient is the client API for YukinoCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YukinoCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type yukinoCacheV2Client struct {
	cc grpc.ClientConnInterface
}

func NewYukinoCacheClient(cc grpc.ClientConnInterface) YukinoCacheClient {
	return &yukinoCacheV2Client{cc}
}

func (c *yukinoCacheV2Client) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, YukinoCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yukinoCacheV2Client) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, YukinoCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yukinoCacheV2Client) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, YukinoCache_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YukinoCacheServer is the server API for YukinoCache service.
// All implementations must embed UnimplementedYukinoCacheServer
// for forward compatibility.
type YukinoCacheServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	Set(context.Context, *Request) (*ResponseForGet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedYukinoCacheServer()
}

// UnimplementedYukinoCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYukinoCacheServer struct{}

func (UnimplementedYukinoCacheServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedYukinoCacheServer) Set(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedYukinoCacheServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedYukinoCacheServer) mustEmbedUnimplementedYukinoCacheServer() {}
func (UnimplementedYukinoCacheServer) testEmbeddedByValue()                     {}

// UnsafeYukinoCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YukinoCacheServer will
// result in compilation errors.
type UnsafeYukinoCacheServer interface {
	mustEmbedUnimplementedYukinoCacheServer()
}

func RegisterYukinoCacheServer(s grpc.ServiceRegistrar, srv YukinoCacheServer) {
	// If the following call pancis, it indicates UnimplementedYukinoCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YukinoCache_ServiceDesc, srv)
}

func _YukinoCache_Get_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YukinoCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YukinoCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(YukinoCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _YukinoCache_Set_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YukinoCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YukinoCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(YukinoCacheServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _YukinoCache_Delete_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YukinoCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YukinoCache_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(YukinoCacheServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// YukinoCache_ServiceDesc is the grpc.ServiceDesc for YukinoCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YukinoCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.YukinoCache",
	HandlerType: (*YukinoCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _YukinoCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _YukinoCache_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _YukinoCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/yukino.proto",
}
